# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e74b6fc578e8bb04ff2b270d06501f7cad6aa9603df5f130a17e73aa365ac2fd97f4e623b03a88a72eb4617f08ffcd0df21053447d39a53bb7145d1c80e0780

test:
  secret_key_base: ddd23a15be6a2a6e4d745c63f5e0e65c71e43afb1e4103fa2468ada4d9e8aea7df6c12f3d8d67d9755dd244bee17c40a485f42e959d9354d0f0647921a2309d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
